name: ton_core
description: A new flutter plugin project.
version: 0.0.1
author: "Vadim Ledyaev <v.o.ledyaev@gmail.com>"
homepage: "https://github.com/voledyaev/ton_core"

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  rxdart: ^0.27.0
  synchronized: ^3.0.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ton_core
        pluginClass: TonCorePlugin
      ios:
        pluginClass: TonCorePlugin
